### ISSUE TITLE
Highlighted text is not updating when text changes

### ISSUE THREAD

**Issue by vcarlucci** [Guyiming/Highlight.Blazor#3]
The highlighted text is not actualized when the content changes during a session. Seems it is only loaded once when page is loaded and even the content changes and a "StateHasChanged()" is given, nothing will update.

**Comment by vcarlucci** [comment]
Here a reproduction logic
(Unfortunately github is not able to display code in a code section properly, so simply copy all content from the next line here)



@page "/Test"
<button @onclick=UpdateCurrentCounterValue>Update</button>
<br />
<br />
<h3>Snippet Viewer</h3>
<CodeHighlight>
    @SoucreCode
</CodeHighlight>

@code {
    string _SourceCode = "Display count result";
    int Counter = 0;

    [Parameter]
    public string SoucreCode
    {
        get{
            return _SourceCode;
        }
        set{
            _SourceCode = value;
            StateHasChanged();
        }
    }
    void UpdateCurrentCounterValue()
    {
        Counter++;
        SoucreCode = "Count result = " + Counter;
    }
}

**Comment by vcarlucci** [comment]
@Guyiming Hi, are you going to investigate in this issue here because this is a main feature I am looking on. I need to change the snipped content and will need instantly the highlighted text between updated. Is it possible to fix that in a certain time range? Otherwise I'll have to look for another solution, even if I really like yours here so far. Thank you very much in advance!

**Comment by Guyiming** [comment]
Hi @vcarlucci， Tonight, I will start trying to solve the two issues you raised since I've been busy with work lately. Once I have a solution, I will push a new version. If you have time, you can also try submitting a pull request. It's not very difficult overall.

**Comment by vcarlucci** [comment]
Hi @Guyiming , thank's for your response. Cool, sounds good! I have not checked your code until now. Maybe I'll find some time for it.

**Comment by Guyiming** [comment]
fixed in 0.1.10

**Comment by vcarlucci** [comment]
Hi #Guyiming, thank you very much for your fast contribution into this issue. 

I have updated according your related version to 0.1.10. Unfortunately now I run directly into an exception, with the same example code on top of this issue.

Here the exception:

`
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'setInnerHtml' ('setInnerHtml' was undefined).
      Error: Could not find 'setInnerHtml' ('setInnerHtml' was undefined).
          at https://localhost:7164/_framework/blazor.webassembly.js:1:328
          at Array.forEach (<anonymous>)
          at a.findFunction (https://localhost:7164/_framework/blazor.webassembly.js:1:296)
          at _ (https://localhost:7164/_framework/blazor.webassembly.js:1:2442)
          at https://localhost:7164/_framework/blazor.webassembly.js:1:3330
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:7164/_framework/blazor.webassembly.js:1:3311)
          at Object.Gt [as invokeJSFromDotNet] (https://localhost:7164/_framework/blazor.webassembly.js:1:62541)
          at Object.Ii (https://localhost:7164/_framework/dotnet.7.0.5.eqs19pya6r.js:5:71974)
          at _mono_wasm_invoke_js_blazor (https://localhost:7164/_framework/dotnet.7.0.5.eqs19pya6r.js:14:103886)
Microsoft.JSInterop.JSException: Could not find 'setInnerHtml' ('setInnerHtml' was undefined).
Error: Could not find 'setInnerHtml' ('setInnerHtml' was undefined).
    at https://localhost:7164/_framework/blazor.webassembly.js:1:328
    at Array.forEach (<anonymous>)
    at a.findFunction (https://localhost:7164/_framework/blazor.webassembly.js:1:296)
    at _ (https://localhost:7164/_framework/blazor.webassembly.js:1:2442)
    at https://localhost:7164/_framework/blazor.webassembly.js:1:3330
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:7164/_framework/blazor.webassembly.js:1:3311)
    at Object.Gt [as invokeJSFromDotNet] (https://localhost:7164/_framework/blazor.webassembly.js:1:62541)
    at Object.Ii (https://localhost:7164/_framework/dotnet.7.0.5.eqs19pya6r.js:5:71974)
    at _mono_wasm_invoke_js_blazor (https://localhost:7164/_framework/dotnet.7.0.5.eqs19pya6r.js:14:103886)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at HighlightBlazor.CodeHighlight.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
`

**Comment by Guyiming** [comment]
Hi @vcarlucci , please clear the browser cache, `Could not find 'setInnerHtml' ('setInnerHtml' was undefined)` mean you use the old version of [highlight-blazor.js](https://github.com/Guyiming/Highlight.Blazor/blob/main/HighlightBlazor/wwwroot/highlight-blazor.js)

**Comment by Guyiming** [comment]
Please note: if you want to update text in csharp code, you should write like this `<CodeHighlight Code=@SourceCode></CodeHighlight>` not the `<CodeHighlight>@SourceCode</CodeHighlight>`

**Comment by vcarlucci** [comment]
@Guyiming, yes clearing the browser cache helped.

So I  have tested this issue and is working now with 01.1.10

Thanks!
